parameters: { }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $webOrigin: '%env(WEB_ORIGIN)%'

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'
