parameters: { }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $webOrigin: '%env(WEB_ORIGIN)%'
      $packageStoragePath: '%env(PACKAGE_STORAGE_PATH)%'

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'
