date.timezone = Asia/Seoul
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
memory_limit = 256M
upload_max_filesize = 11M
post_max_size = 11M
max_execution_time = 60
session.cookie_httponly = 1
session.cookie_samesite = Lax
opcache.enable = 1
opcache.validate_timestamps = 1
