#!/bin/sh

set -eu

REPOSITORY_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
GITHUB_REPOSITORY="${GIBYEOL_GITHUB_REPOSITORY:-yt4307/gibyeol}"
PREVIEW_FRONTEND_PORT="${DEV_FRONTEND_PORT:-3001}"
PREVIEW_BACKEND_PORT="${DEV_BACKEND_PORT:-8081}"
PREVIEW_WEB_ORIGIN="http://localhost:${PREVIEW_FRONTEND_PORT}"
PREVIEW_API_ORIGIN="http://localhost:${PREVIEW_BACKEND_PORT}"

if ! command -v gh >/dev/null 2>&1; then
    echo "GitHub CLI(gh)가 필요합니다." >&2
    exit 1
fi

github_variable() {
    gh variable get "$1" --repo "${GITHUB_REPOSITORY}"
}

PREVIEW_PROJECT_ID=$(github_variable NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID)
PREVIEW_RPC_URL=$(github_variable NEXT_PUBLIC_RPC_URL)
PREVIEW_CONTRACT_ADDRESS=$(github_variable NEXT_PUBLIC_GIBYEOL_CONTRACT_ADDRESS)
PREVIEW_DEPLOYMENT_BLOCK=$(github_variable NEXT_PUBLIC_DEPLOYMENT_BLOCK)

cd "${REPOSITORY_ROOT}"
env \
    DEV_FRONTEND_PORT="${PREVIEW_FRONTEND_PORT}" \
    DEV_BACKEND_PORT="${PREVIEW_BACKEND_PORT}" \
    DEV_WEB_ORIGIN="${PREVIEW_WEB_ORIGIN}" \
    DEV_API_ORIGIN="${PREVIEW_API_ORIGIN}" \
    DEV_NEXT_PUBLIC_API_BASE_URL="${PREVIEW_API_ORIGIN}/api/v1" \
    NEXT_PUBLIC_CHAIN_ID=84532 \
    DEV_NEXT_PUBLIC_RPC_URL="${PREVIEW_RPC_URL}" \
    NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID="${PREVIEW_PROJECT_ID}" \
    NEXT_PUBLIC_GIBYEOL_CONTRACT_ADDRESS="${PREVIEW_CONTRACT_ADDRESS}" \
    NEXT_PUBLIC_DEPLOYMENT_BLOCK="${PREVIEW_DEPLOYMENT_BLOCK}" \
    WEB_ORIGIN="${PREVIEW_WEB_ORIGIN}" \
    CHAIN_ID=84532 \
    BASE_RPC_URL="${PREVIEW_RPC_URL}" \
    GIBYEOL_CONTRACT_ADDRESS="${PREVIEW_CONTRACT_ADDRESS}" \
    CONTRACT_DEPLOYMENT_BLOCK="${PREVIEW_DEPLOYMENT_BLOCK}" \
    docker compose up -d --force-recreate backend frontend

echo "Base Sepolia preview: ${PREVIEW_WEB_ORIGIN}/inbox/"
